[package]
name = "spdlog-src"
version = "0.1.0"
authors = ["songww <sww4718168@163.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1"
